<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DistrictModel;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
            ['name' => 'Kullu', 'statecode' => 'HP'],
            ['name' => 'Mandi', 'statecode' => 'HP'],
            ['name' => 'Bilaspur', 'statecode' => 'HP'],
            ['name' => 'Hamirpur', 'statecode' => 'HP'],
            ['name' => 'Solan', 'statecode' => 'HP'],
            ['name' => 'Shimla', 'statecode' => 'HP'],
            ['name' => 'Chamba', 'statecode' => 'HP'],
            ['name' => 'Kangra', 'statecode' => 'HP'],
            ['name' => 'Kinnaur', 'statecode' => 'HP'],
            ['name' => 'Una', 'statecode' => 'HP'],
            ['name' => 'Lahaul and Spiti', 'statecode' => 'HP'],
            ['name' => 'Sirmaur', 'statecode' => 'HP'],

            ['name' => 'East Godavari', 'statecode' => 'AP'],
            ['name' => 'West Godavari', 'statecode' => 'AP'],
            ['name' => 'Visakhapatnam', 'statecode' => 'AP'],
            ['name' => 'Srikakulam', 'statecode' => 'AP'],
            ['name' => 'Krishna', 'statecode' => 'AP'],
            ['name' => 'Kurnool', 'statecode' => 'AP'],
            ['name' => 'Guntur', 'statecode' => 'AP'],
            ['name' => 'Prakasam', 'statecode' => 'AP'],
            ['name' => 'Vizianagaram', 'statecode' => 'AP'],
            ['name' => 'Anantapur', 'statecode' => 'AP'],
            ['name' => 'Chittoor', 'statecode' => 'AP'],
            ['name' => 'Kadapa', 'statecode' => 'AP'],
            ['name' => 'Eluru', 'statecode' => 'AP'],
            ['name' => 'Bapatla', 'statecode' => 'AP'],
            ['name' => 'YSR District', 'statecode' => 'AP'],
            ['name' => 'Kakinada', 'statecode' => 'AP'],
            ['name' => 'Sri Potti Sriramulu Nellore', 'statecode' => 'AP'],
            ['name' => 'Nellore', 'statecode' => 'AP'],
            ['name' => 'Nandyal', 'statecode' => 'AP'],
            ['name' => 'Vijayawada', 'statecode' => 'AP'],
            ['name' => 'Anakapalli', 'statecode' => 'AP'],
            ['name' => 'Tirupati', 'statecode' => 'AP'],
            ['name' => 'Palnadu', 'statecode' => 'AP'],
            ['name' => 'Machilipatnam', 'statecode' => 'AP'],
            ['name' => 'Parvathipuram Manyam', 'statecode' => 'AP'],
            ['name' => 'Alluri Sitharama Raju', 'statecode' => 'AP'],

            ['name' => 'Anjaw', 'statecode' => 'AR'],
            ['name' => 'Changlang', 'statecode' => 'AR'],
            ['name' => 'Kamle', 'statecode' => 'AR'],
            ['name' => 'Kra Daadi', 'statecode' => 'AR'],
            ['name' => 'Kurung Kumey', 'statecode' => 'AR'],
            ['name' => 'Lepa-Rada', 'statecode' => 'AR'],
            ['name' => 'Lohit', 'statecode' => 'AR'],
            ['name' => 'Longding', 'statecode' => 'AR'],
            ['name' => 'Namsai', 'statecode' => 'AR'],
            ['name' => 'Pakke-Kessang', 'statecode' => 'AR'],
            ['name' => 'Papum Pare', 'statecode' => 'AR'],
            ['name' => 'Shi-Yomi', 'statecode' => 'AR'],
            ['name' => 'Siang', 'statecode' => 'AR'],
            ['name' => 'Tawang', 'statecode' => 'AR'],
            ['name' => 'Tirap', 'statecode' => 'AR'],
            ['name' => 'Lower Dibang Valley', 'statecode' => 'AR'],
            ['name' => 'Dibang Valley', 'statecode' => 'AR'],
            ['name' => 'East Kameng', 'statecode' => 'AR'],
            ['name' => 'West Kameng', 'statecode' => 'AR'],
            ['name' => 'East Siang', 'statecode' => 'AR'],
            ['name' => 'Lower Siang', 'statecode' => 'AR'],
            ['name' => 'Upper Siang', 'statecode' => 'AR'],
            ['name' => 'West Siang', 'statecode' => 'AR'],
            ['name' => 'Lower Subansiri', 'statecode' => 'AR'],
            ['name' => 'Upper Subansiri', 'statecode' => 'AR'],
            
            ['name' => 'Baksa', 'statecode' => 'AS'],
            ['name' => 'Barpeta', 'statecode' => 'AS'],
            ['name' => 'Bongaigaon', 'statecode' => 'AS'],
            ['name' => 'Cachar', 'statecode' => 'AS'],
            ['name' => 'Charaideo', 'statecode' => 'AS'],
            ['name' => 'Chirang', 'statecode' => 'AS'],
            ['name' => 'Darrang', 'statecode' => 'AS'],
            ['name' => 'Dhemaji', 'statecode' => 'AS'],
            ['name' => 'Dhubri', 'statecode' => 'AS'],
            ['name' => 'Dibrugarh', 'statecode' => 'AS'],
            ['name' => 'Dima Hasao', 'statecode' => 'AS'],
            ['name' => 'Goalpara', 'statecode' => 'AS'],
            ['name' => 'Golaghat', 'statecode' => 'AS'],
            ['name' => 'Hailakandi', 'statecode' => 'AS'],
            ['name' => 'Jorhat', 'statecode' => 'AS'],
            ['name' => 'Kamrup Metropolitan', 'statecode' => 'AS'],
            ['name' => 'Kamrup', 'statecode' => 'AS'],
            ['name' => 'Karbi Anglong', 'statecode' => 'AS'],
            ['name' => 'Karimganj', 'statecode' => 'AS'],
            ['name' => 'Kokrajhar', 'statecode' => 'AS'],
            ['name' => 'Lakhimpur', 'statecode' => 'AS'],
            ['name' => 'Majuli', 'statecode' => 'AS'],
            ['name' => 'Morigaon', 'statecode' => 'AS'],
            ['name' => 'Nagaon', 'statecode' => 'AS'],
            ['name' => 'Nalbari', 'statecode' => 'AS'],
            ['name' => 'Sivasagar', 'statecode' => 'AS'],
            ['name' => 'Sonitpur', 'statecode' => 'AS'],
            ['name' => 'South Salmara-Mankachar[', 'statecode' => 'AS'],
            ['name' => 'Tinsukia', 'statecode' => 'AS'],
            ['name' => 'Udalguri', 'statecode' => 'AS'],
            ['name' => 'West Karbi Anglong', 'statecode' => 'AS'],
            
            ['name' => 'Araria', 'statecode' => 'BR'],
            ['name' => 'Arwal', 'statecode' => 'BR'],
            ['name' => 'Aurangabad', 'statecode' => 'BR'],
            ['name' => 'Banka', 'statecode' => 'BR'],
            ['name' => 'Begusarai', 'statecode' => 'BR'],
            ['name' => 'Bhagalpur', 'statecode' => 'BR'],
            ['name' => 'Bhojpur', 'statecode' => 'BR'],
            ['name' => 'Buxar', 'statecode' => 'BR'],
            ['name' => 'Darbhanga', 'statecode' => 'BR'],
            ['name' => 'East Champaran', 'statecode' => 'BR'],
            ['name' => 'Gaya', 'statecode' => 'BR'],
            ['name' => 'Gopalganj', 'statecode' => 'BR'],
            ['name' => 'Jamui', 'statecode' => 'BR'],
            ['name' => 'Jehanabad', 'statecode' => 'BR'],
            ['name' => 'Kaimur', 'statecode' => 'BR'],
            ['name' => 'Katihar', 'statecode' => 'BR'],
            ['name' => 'Khagaria', 'statecode' => 'BR'],
            ['name' => 'Kishanganj', 'statecode' => 'BR'],
            ['name' => 'Lakhisarai', 'statecode' => 'BR'],
            ['name' => 'Madhepura', 'statecode' => 'BR'],
            ['name' => 'Madhubani', 'statecode' => 'BR'],
            ['name' => 'Munger', 'statecode' => 'BR'],
            ['name' => 'Muzaffarpur', 'statecode' => 'BR'],
            ['name' => 'Nalanda', 'statecode' => 'BR'],
            ['name' => 'Nawada', 'statecode' => 'BR'],
            ['name' => 'Patna', 'statecode' => 'BR'],
            ['name' => 'Purnia', 'statecode' => 'BR'],
            ['name' => 'Rohtas', 'statecode' => 'BR'],
            ['name' => 'Saharsa', 'statecode' => 'BR'],
            ['name' => 'Samastipur', 'statecode' => 'BR'],
            ['name' => 'Saran', 'statecode' => 'BR'],
            ['name' => 'Sheikhpura', 'statecode' => 'BR'],
            ['name' => 'Sheohar', 'statecode' => 'BR'],
            ['name' => 'Sitamarhi', 'statecode' => 'BR'],
            ['name' => 'Siwan', 'statecode' => 'BR'],
            ['name' => 'Supaul', 'statecode' => 'BR'],
            ['name' => 'Vaishali', 'statecode' => 'BR'],
            ['name' => 'West Champaran', 'statecode' => 'BR'],
            
            ['name' => 'Raipur', 'statecode' => 'CG'],
            ['name' => 'Balod', 'statecode' => 'CG'],
            ['name' => 'Baloda Bazar', 'statecode' => 'CG'],
            ['name' => 'Balrampur', 'statecode' => 'CG'],
            ['name' => 'Bastar', 'statecode' => 'CG'],
            ['name' => 'Bemetara', 'statecode' => 'CG'],
            ['name' => 'Bijapur', 'statecode' => 'CG'],
            ['name' => 'Bilaspur', 'statecode' => 'CG'],
            ['name' => 'Dantewada', 'statecode' => 'CG'],
            ['name' => 'Dhamtari', 'statecode' => 'CG'],
            ['name' => 'Durg', 'statecode' => 'CG'],
            ['name' => 'Gariaband', 'statecode' => 'CG'],
            ['name' => 'Gaurella-Pendra-Marwahi', 'statecode' => 'CG'],
            ['name' => 'Janjgir-Champa', 'statecode' => 'CG'],
            ['name' => 'Jashpur', 'statecode' => 'CG'],
            ['name' => 'Kabirdham', 'statecode' => 'CG'],
            ['name' => 'Kanker', 'statecode' => 'CG'],
            ['name' => 'Kondagaon', 'statecode' => 'CG'],
            ['name' => 'Khairagarh-Chhuikhadan-Gandai', 'statecode' => 'CG'],
            ['name' => 'Korba', 'statecode' => 'CG'],
            ['name' => 'Koriya', 'statecode' => 'CG'],
            ['name' => 'Mahasamund', 'statecode' => 'CG'],
            ['name' => 'Manendragarh-Chirmiri-Bharatpur', 'statecode' => 'CG'],
            ['name' => 'Mohla-Manpur- Ambagarh Chowki', 'statecode' => 'CG'],
            ['name' => 'Mungeli', 'statecode' => 'CG'],
            ['name' => 'Narayanpur', 'statecode' => 'CG'],
            ['name' => 'Raigarh', 'statecode' => 'CG'],
            ['name' => 'Rajnandgaon', 'statecode' => 'CG'],
            ['name' => 'Sarangarh-Bilaigarh', 'statecode' => 'CG'],
            ['name' => 'Sakti', 'statecode' => 'CG'],
            ['name' => 'Sukma', 'statecode' => 'CG'],
            ['name' => 'Surajpur', 'statecode' => 'CG'],
            ['name' => 'Surguja', 'statecode' => 'CG'],
            
            ['name' => 'North Goa', 'statecode' => 'GA'],
            ['name' => 'South Goa', 'statecode' => 'GA'],
            
            ['name' => 'Ahmedabad', 'statecode' => 'GJ'],
            ['name' => 'Amreli', 'statecode' => 'GJ'],
            ['name' => 'Anand', 'statecode' => 'GJ'],
            ['name' => 'Aravali', 'statecode' => 'GJ'],
            ['name' => 'Banaskantha', 'statecode' => 'GJ'],
            ['name' => 'Bharuch', 'statecode' => 'GJ'],
            ['name' => 'Bhavnagar', 'statecode' => 'GJ'],
            ['name' => 'Botad', 'statecode' => 'GJ'],
            ['name' => 'Chhota Udaipur', 'statecode' => 'GJ'],
            ['name' => 'Dahod', 'statecode' => 'GJ'],
            ['name' => 'Dang', 'statecode' => 'GJ'],
            ['name' => 'Devbhumi Dwarka', 'statecode' => 'GJ'],
            ['name' => 'Gandhinagar', 'statecode' => 'GJ'],
            ['name' => 'Gir Somnath', 'statecode' => 'GJ'],
            ['name' => 'Jamnagar', 'statecode' => 'GJ'],
            ['name' => 'Junagarh', 'statecode' => 'GJ'],
            ['name' => 'Kheda', 'statecode' => 'GJ'],
            ['name' => 'Kutch', 'statecode' => 'GJ'],
            ['name' => 'Mahisagar', 'statecode' => 'GJ'],
            ['name' => 'Mehsana', 'statecode' => 'GJ'],
            ['name' => 'Morbi', 'statecode' => 'GJ'],
            ['name' => 'Narmada', 'statecode' => 'GJ'],
            ['name' => 'Navsari', 'statecode' => 'GJ'],
            ['name' => 'Panchmahal', 'statecode' => 'GJ'],
            ['name' => 'Patan', 'statecode' => 'GJ'],
            ['name' => 'Porbandar', 'statecode' => 'GJ'],
            ['name' => 'Rajkot', 'statecode' => 'GJ'],
            ['name' => 'Sabarkantha', 'statecode' => 'GJ'],
            ['name' => 'Surat', 'statecode' => 'GJ'],
            ['name' => 'Surendranagar', 'statecode' => 'GJ'],
            ['name' => 'Tapi', 'statecode' => 'GJ'],
            ['name' => 'Vadodara', 'statecode' => 'GJ'],
            ['name' => 'Valsad', 'statecode' => 'GJ'],
            
            ['name' => 'Ambala', 'statecode' => 'HR'],
            ['name' => 'Bhiwani', 'statecode' => 'HR'],
            ['name' => 'Charkhi Dadri', 'statecode' => 'HR'],
            ['name' => 'Faridabad', 'statecode' => 'HR'],
            ['name' => 'Fatehabad', 'statecode' => 'HR'],
            ['name' => 'Gurugram', 'statecode' => 'HR'],
            ['name' => 'Hisar', 'statecode' => 'HR'],
            ['name' => 'Jhajjar', 'statecode' => 'HR'],
            ['name' => 'Jind', 'statecode' => 'HR'],
            ['name' => 'Kaithal', 'statecode' => 'HR'],
            ['name' => 'Karnal', 'statecode' => 'HR'],
            ['name' => 'Kurukshetra', 'statecode' => 'HR'],
            ['name' => 'Mahendragarh', 'statecode' => 'HR'],
            ['name' => 'Nuh', 'statecode' => 'HR'],
            ['name' => 'Palwal', 'statecode' => 'HR'],
            ['name' => 'Panchkula', 'statecode' => 'HR'],
            ['name' => 'Panipat', 'statecode' => 'HR'],
            ['name' => 'Rewari', 'statecode' => 'HR'],
            ['name' => 'Rohtak', 'statecode' => 'HR'],
            ['name' => 'Sirsa', 'statecode' => 'HR'],
            ['name' => 'Sonipat', 'statecode' => 'HR'],
            ['name' => 'Yamunanagar', 'statecode' => 'HR'],
            
            ['name' => 'Bokaro', 'statecode' => 'JH'],
            ['name' => 'Chatra', 'statecode' => 'JH'],
            ['name' => 'Deoghar', 'statecode' => 'JH'],
            ['name' => 'Dhanbad', 'statecode' => 'JH'],
            ['name' => 'Dumka', 'statecode' => 'JH'],
            ['name' => 'East Singhbhum', 'statecode' => 'JH'],
            ['name' => 'Garhwa', 'statecode' => 'JH'],
            ['name' => 'Giridih', 'statecode' => 'JH'],
            ['name' => 'Godda', 'statecode' => 'JH'],
            ['name' => 'Gumla', 'statecode' => 'JH'],
            ['name' => 'Hazaribag', 'statecode' => 'JH'],
            ['name' => 'Jamtara', 'statecode' => 'JH'],
            ['name' => 'Khunti', 'statecode' => 'JH'],
            ['name' => 'Koderma', 'statecode' => 'JH'],
            ['name' => 'Latehar', 'statecode' => 'JH'],
            ['name' => 'Lohardaga', 'statecode' => 'JH'],
            ['name' => 'Pakur', 'statecode' => 'JH'],
            ['name' => 'Palamu', 'statecode' => 'JH'],
            ['name' => 'Ramgarh', 'statecode' => 'JH'],
            ['name' => 'Ranchi', 'statecode' => 'JH'],
            ['name' => 'Sahibganj', 'statecode' => 'JH'],
            ['name' => 'Seraikela-Kharsawan', 'statecode' => 'JH'],
            ['name' => 'Simdega', 'statecode' => 'JH'],
            ['name' => 'West Singhbhum', 'statecode' => 'JH'],
            
            ['name' => 'Bagalkote', 'statecode' => 'KA'],
            ['name' => 'Bengaluru Urban', 'statecode' => 'KA'],
            ['name' => 'Bengaluru Rural', 'statecode' => 'KA'],
            ['name' => 'Belagavi', 'statecode' => 'KA'],
            ['name' => 'Ballary', 'statecode' => 'KA'],
            ['name' => 'Bidar', 'statecode' => 'KA'],
            ['name' => 'Vijayapura', 'statecode' => 'KA'],
            ['name' => 'Chamarajanagara', 'statecode' => 'KA'],
            ['name' => 'Chikkaballapura', 'statecode' => 'KA'],
            ['name' => 'Chikkamagaluru', 'statecode' => 'KA'],
            ['name' => 'Chitradurga', 'statecode' => 'KA'],
            ['name' => 'Dakshina Kannada', 'statecode' => 'KA'],
            ['name' => 'Davanagere', 'statecode' => 'KA'],
            ['name' => 'Dharwad', 'statecode' => 'KA'],
            ['name' => 'Gadag', 'statecode' => 'KA'],
            ['name' => 'Kalaburagi', 'statecode' => 'KA'],
            ['name' => 'Hassan', 'statecode' => 'KA'],
            ['name' => 'Haveri', 'statecode' => 'KA'],
            ['name' => 'Kodagu', 'statecode' => 'KA'],
            ['name' => 'Kolara', 'statecode' => 'KA'],
            ['name' => 'Koppala', 'statecode' => 'KA'],
            ['name' => 'Mandya', 'statecode' => 'KA'],
            ['name' => 'Mysuru', 'statecode' => 'KA'],
            ['name' => 'Raichuru', 'statecode' => 'KA'],
            ['name' => 'Ramanagara', 'statecode' => 'KA'],
            ['name' => 'Shivamogga', 'statecode' => 'KA'],
            ['name' => 'Tumakuru', 'statecode' => 'KA'],
            ['name' => 'Udupi', 'statecode' => 'KA'],
            ['name' => 'Uttara Kannada', 'statecode' => 'KA'],
            ['name' => 'Vijayanagara', 'statecode' => 'KA'],
            ['name' => 'Yadgiri', 'statecode' => 'KA'],
            
            ['name' => 'Alappuzha', 'statecode' => 'KL'],
            ['name' => 'Ernakulam', 'statecode' => 'KL'],
            ['name' => 'Idukki', 'statecode' => 'KL'],
            ['name' => 'Kannur', 'statecode' => 'KL'],
            ['name' => 'Kasaragod', 'statecode' => 'KL'],
            ['name' => 'Kollam', 'statecode' => 'KL'],
            ['name' => 'Kottayam', 'statecode' => 'KL'],
            ['name' => 'Kozhikode', 'statecode' => 'KL'],
            ['name' => 'Malappuram', 'statecode' => 'KL'],
            ['name' => 'Palakkad', 'statecode' => 'KL'],
            ['name' => 'Pathanamthitta', 'statecode' => 'KL'],
            ['name' => 'Thiruvananthapuram', 'statecode' => 'KL'],
            ['name' => 'Thrissur', 'statecode' => 'KL'],
            ['name' => 'Wayanad', 'statecode' => 'KL'],  
            
            ['name' => 'Agar Malwa', 'statecode' => 'MP'],  
            ['name' => 'Alirajpur', 'statecode' => 'MP'], 
            ['name' => 'Anuppur', 'statecode' => 'MP'], 
            ['name' => 'Ashoknagar', 'statecode' => 'MP'], 
            ['name' => 'Balaghat', 'statecode' => 'MP'], 
            ['name' => 'Barwan', 'statecode' => 'MP'], 
            ['name' => 'Betul', 'statecode' => 'MP'], 
            ['name' => 'Bhind', 'statecode' => 'MP'], 
            ['name' => 'Bhopal', 'statecode' => 'MP'], 
            ['name' => 'Burhanpur', 'statecode' => 'MP'], 
            ['name' => 'Chhatarpur', 'statecode' => 'MP'], 
            ['name' => 'Chhindwara', 'statecode' => 'MP'], 
            ['name' => 'Damoh', 'statecode' => 'MP'], 
            ['name' => 'Datia', 'statecode' => 'MP'], 
            ['name' => 'Dewas', 'statecode' => 'MP'], 
            ['name' => 'Dhar', 'statecode' => 'MP'], 
            ['name' => 'Dindori', 'statecode' => 'MP'], 
            ['name' => 'East Nimar', 'statecode' => 'MP'], 
            ['name' => 'Guna', 'statecode' => 'MP'], 
            ['name' => 'Gwalior', 'statecode' => 'MP'], 
            ['name' => 'Harda', 'statecode' => 'MP'], 
            ['name' => 'Hoshangabad', 'statecode' => 'MP'], 
            ['name' => 'Indore', 'statecode' => 'MP'], 
            ['name' => 'Jabalpur', 'statecode' => 'MP'], 
            ['name' => 'Jhabua', 'statecode' => 'MP'], 
            ['name' => 'Katni', 'statecode' => 'MP'], 
            ['name' => 'Mandla', 'statecode' => 'MP'], 
            ['name' => 'Mandsaur', 'statecode' => 'MP'], 
            ['name' => 'Morena', 'statecode' => 'MP'], 
            ['name' => 'Narsinghpur', 'statecode' => 'MP'], 
            ['name' => 'Neemuch', 'statecode' => 'MP'], 
            ['name' => 'Niwari', 'statecode' => 'MP'], 
            ['name' => 'Panna', 'statecode' => 'MP'], 
            ['name' => 'Raisen', 'statecode' => 'MP'], 
            ['name' => 'Rajgarh', 'statecode' => 'MP'], 
            ['name' => 'Ratlam', 'statecode' => 'MP'], 
            ['name' => 'Rewa', 'statecode' => 'MP'], 
            ['name' => 'Sagar', 'statecode' => 'MP'], 
            ['name' => 'Satna', 'statecode' => 'MP'], 
            ['name' => 'Sehore', 'statecode' => 'MP'], 
            ['name' => 'Seoni', 'statecode' => 'MP'], 
            ['name' => 'Shahdol', 'statecode' => 'MP'], 
            ['name' => 'Shajapur', 'statecode' => 'MP'], 
            ['name' => 'Sheopur', 'statecode' => 'MP'], 
            ['name' => 'Shivpuri', 'statecode' => 'MP'], 
            ['name' => 'Sidhi', 'statecode' => 'MP'], 
            ['name' => 'Singrauli', 'statecode' => 'MP'], 
            ['name' => 'Tikamgarh', 'statecode' => 'MP'], 
            ['name' => 'Ujjain', 'statecode' => 'MP'], 
            ['name' => 'Umaria', 'statecode' => 'MP'], 
            ['name' => 'Vidisha', 'statecode' => 'MP'], 
            ['name' => 'West Nimar', 'statecode' => 'MP'], 
             
            ['name' => 'Ahmednagar', 'statecode' => 'MH'], 
            ['name' => 'Akola', 'statecode' => 'MH'],
            ['name' => 'Amravati', 'statecode' => 'MH'],
            ['name' => 'Aurangabad', 'statecode' => 'MH'],
            ['name' => 'Beed', 'statecode' => 'MH'],
            ['name' => 'Bhandara', 'statecode' => 'MH'],
            ['name' => 'Buldhana', 'statecode' => 'MH'],
            ['name' => 'Chandrapur', 'statecode' => 'MH'],
            ['name' => 'Dhule', 'statecode' => 'MH'],
            ['name' => 'Gadchiroli', 'statecode' => 'MH'],
            ['name' => 'Gondia', 'statecode' => 'MH'],
            ['name' => 'Hingoli', 'statecode' => 'MH'],
            ['name' => 'Jalgaon', 'statecode' => 'MH'],
            ['name' => 'Jalna', 'statecode' => 'MH'],
            ['name' => 'Kolhapur', 'statecode' => 'MH'],
            ['name' => 'Latur', 'statecode' => 'MH'],
            ['name' => 'Mumbai City', 'statecode' => 'MH'],
            ['name' => 'Mumbai Suburban', 'statecode' => 'MH'],
            ['name' => 'Nagpur', 'statecode' => 'MH'],
            ['name' => 'Nanded', 'statecode' => 'MH'],
            ['name' => 'Nandurbar', 'statecode' => 'MH'],
            ['name' => 'Nashik', 'statecode' => 'MH'],
            ['name' => 'Osmanabad', 'statecode' => 'MH'],
            ['name' => 'Palghar', 'statecode' => 'MH'],
            ['name' => 'Parbhani', 'statecode' => 'MH'],
            ['name' => 'Pune', 'statecode' => 'MH'],
            ['name' => 'Raigad', 'statecode' => 'MH'],
            ['name' => 'Sangli', 'statecode' => 'MH'],
            ['name' => 'Satara', 'statecode' => 'MH'],
            ['name' => 'Sindhudurg', 'statecode' => 'MH'],
            ['name' => 'Solapur', 'statecode' => 'MH'],
            ['name' => 'Thane', 'statecode' => 'MH'],
            ['name' => 'Wardha', 'statecode' => 'MH'],
            ['name' => 'Washim', 'statecode' => 'MH'],
            ['name' => 'Yavatmal', 'statecode' => 'MH'],
            ['name' => 'Ratnagiri', 'statecode' => 'MH'],
            
            ['name' => 'Bishnupur', 'statecode' => 'MN'],
            ['name' => 'Chandel', 'statecode' => 'MN'],
            ['name' => 'Churachandpur', 'statecode' => 'MN'],
            ['name' => 'Imphal East', 'statecode' => 'MN'],
            ['name' => 'Imphal West', 'statecode' => 'MN'],
            ['name' => 'Jiribam', 'statecode' => 'MN'],
            ['name' => 'Kakching', 'statecode' => 'MN'],
            ['name' => 'Kamjong', 'statecode' => 'MN'],
            ['name' => 'Kangpokpi', 'statecode' => 'MN'],
            ['name' => 'Noney', 'statecode' => 'MN'],
            ['name' => 'Pherzawl', 'statecode' => 'MN'],
            ['name' => 'Senapati', 'statecode' => 'MN'],
            ['name' => 'Tamenglong', 'statecode' => 'MN'],
            ['name' => 'Tengnoupal', 'statecode' => 'MN'],
            ['name' => 'Thoubal', 'statecode' => 'MN'],
            ['name' => 'Ukhrul', 'statecode' => 'MN'],
            
            ['name' => 'North Garo Hills', 'statecode' => 'ML'],
            ['name' => 'East Garo Hills', 'statecode' => 'ML'],
            ['name' => 'South Garo Hills', 'statecode' => 'ML'],
            ['name' => 'West Garo Hills', 'statecode' => 'ML'],
            ['name' => 'South West Garo Hills', 'statecode' => 'ML'],
            ['name' => 'West Jaintia Hills', 'statecode' => 'ML'],
            ['name' => 'East Jaintia Hills', 'statecode' => 'ML'],
            ['name' => 'East Khasi Hills', 'statecode' => 'ML'],
            ['name' => 'West Khasi Hills', 'statecode' => 'ML'],
            ['name' => 'South West Khasi Hills', 'statecode' => 'ML'],
            ['name' => 'Eastern West Khasi Hills', 'statecode' => 'ML'],
            ['name' => 'Ri-Bhoi', 'statecode' => 'ML'],
            
            ['name' => 'Aizawl', 'statecode' => 'MZ'],
            ['name' => 'Hnahthial', 'statecode' => 'MZ'],
            ['name' => 'Kolasib', 'statecode' => 'MZ'],
            ['name' => 'Lunglei', 'statecode' => 'MZ'],
            ['name' => 'Saiha', 'statecode' => 'MZ'],
            ['name' => 'Serchhip', 'statecode' => 'MZ'],
            ['name' => 'Champhai', 'statecode' => 'MZ'],
            ['name' => 'Khawzawl', 'statecode' => 'MZ'],
            ['name' => 'Lawngtlai', 'statecode' => 'MZ'],
            ['name' => 'Mamit', 'statecode' => 'MZ'],
            ['name' => 'Saitual', 'statecode' => 'MZ'],
            
            ['name' => 'Dimapur', 'statecode' => 'NL'],
            ['name' => 'Kohima', 'statecode' => 'NL'],
            ['name' => 'Longling', 'statecode' => 'NL'],
            ['name' => 'Chumoukedima', 'statecode' => 'NL'],
            ['name' => 'Kiphire', 'statecode' => 'NL'],
            ['name' => 'Mokukchung', 'statecode' => 'NL'],
            ['name' => 'Niuland', 'statecode' => 'NL'],
            ['name' => 'Moklak', 'statecode' => 'NL'],
            ['name' => 'Mon', 'statecode' => 'NL'],
            ['name' => 'Tseminyu', 'statecode' => 'NL'],
            ['name' => 'Shamator', 'statecode' => 'NL'],
            ['name' => 'Phek', 'statecode' => 'NL'],
            ['name' => 'Peren', 'statecode' => 'NL'],
            ['name' => 'Zunheboto', 'statecode' => 'NL'],
            ['name' => 'Tuensang', 'statecode' => 'NL'],
            ['name' => 'Wokha', 'statecode' => 'NL'],
            
            ['name' => 'Angul', 'statecode' => 'OD'],
            ['name' => 'Balasore', 'statecode' => 'OD'],
            ['name' => 'Boudh', 'statecode' => 'OD'],
            ['name' => 'Balangir', 'statecode' => 'OD'],
            ['name' => 'Bhadrak', 'statecode' => 'OD'],
            ['name' => 'Gajapati', 'statecode' => 'OD'],
            ['name' => 'Bargarh', 'statecode' => 'OD'],
            ['name' => 'Cuttack', 'statecode' => 'OD'],
            ['name' => 'Ganjam', 'statecode' => 'OD'],
            ['name' => 'Deogarh', 'statecode' => 'OD'],
            ['name' => 'Jagatsinghpur', 'statecode' => 'OD'],
            ['name' => 'Kalahandi', 'statecode' => 'OD'],
            ['name' => 'Dhenkanal', 'statecode' => 'OD'],
            ['name' => 'Jajpur', 'statecode' => 'OD'],
            ['name' => 'Kandhamai', 'statecode' => 'OD'],
            ['name' => 'Koraput', 'statecode' => 'OD'],
            ['name' => 'Malkangiri', 'statecode' => 'OD'],
            ['name' => 'Nabarangpur', 'statecode' => 'OD'],
            ['name' => 'Nuapada', 'statecode' => 'OD'],
            ['name' => 'Rayagada', 'statecode' => 'OD'],
            ['name' => 'Puri', 'statecode' => 'OD'],
            ['name' => 'Nayagarh', 'statecode' => 'OD'],
            ['name' => 'Mayurbhanj', 'statecode' => 'OD'],
            ['name' => 'Khordha', 'statecode' => 'OD'],
            ['name' => 'Kendrapada', 'statecode' => 'OD'],
            ['name' => 'Jharsuguda', 'statecode' => 'OD'],
            ['name' => 'Kendujhar', 'statecode' => 'OD'],
            ['name' => 'Sambalpur', 'statecode' => 'OD'],
            ['name' => 'Subarnapur', 'statecode' => 'OD'],
            ['name' => 'Sundargarh', 'statecode' => 'OD'],
            
            ['name' => 'Amritsar', 'statecode' => 'PB'],
            ['name' => 'Barnala', 'statecode' => 'PB'],
            ['name' => 'Bathinda', 'statecode' => 'PB'],
            ['name' => 'Faridkot', 'statecode' => 'PB'],
            ['name' => 'Fatehgarh Sahib', 'statecode' => 'PB'],
            ['name' => 'Firozpur', 'statecode' => 'PB'],
            ['name' => 'Fazilka', 'statecode' => 'PB'],
            ['name' => 'Gurdaspur', 'statecode' => 'PB'],
            ['name' => 'Hoshiarpur', 'statecode' => 'PB'],
            ['name' => 'Jalandhar', 'statecode' => 'PB'],
            ['name' => 'Kapurthala', 'statecode' => 'PB'],
            ['name' => 'Ludhiana', 'statecode' => 'PB'],
            ['name' => 'Malerkotla', 'statecode' => 'PB'],
            ['name' => 'Mansa', 'statecode' => 'PB'],
            ['name' => 'Moga', 'statecode' => 'PB'],
            ['name' => 'Sri Muktsar Sahib', 'statecode' => 'PB'],
            ['name' => 'Pathankot', 'statecode' => 'PB'],
            ['name' => 'Patiala', 'statecode' => 'PB'],
            ['name' => 'Rupnagar', 'statecode' => 'PB'],
            ['name' => 'Sahibzada Ajit Singh Nagar', 'statecode' => 'PB'],
            ['name' => 'Sangrur', 'statecode' => 'PB'],
            ['name' => 'Shahid Bhagat Singh Nagar', 'statecode' => 'PB'],
            ['name' => 'Tarn Taran', 'statecode' => 'PB'],
            
            ['name' => 'Ajmer', 'statecode' => 'RJ'],
            ['name' => 'Alwar', 'statecode' => 'RJ'],
            ['name' => 'Banswara', 'statecode' => 'RJ'],
            ['name' => 'Baran', 'statecode' => 'RJ'],
            ['name' => 'Barmer', 'statecode' => 'RJ'],
            ['name' => 'Bharatpur', 'statecode' => 'RJ'],
            ['name' => 'Bhilwara', 'statecode' => 'RJ'],
            ['name' => 'Bikaner', 'statecode' => 'RJ'],
            ['name' => 'Bundi', 'statecode' => 'RJ'],
            ['name' => 'Chittorgarh', 'statecode' => 'RJ'],
            ['name' => 'Churu', 'statecode' => 'RJ'],
            ['name' => 'Dausa', 'statecode' => 'RJ'],
            ['name' => 'Dholpur', 'statecode' => 'RJ'],
            ['name' => 'Dungarpur', 'statecode' => 'RJ'],
            ['name' => 'Hanumangarh', 'statecode' => 'RJ'],
            ['name' => 'Jaipur', 'statecode' => 'RJ'],
            ['name' => 'Jaisalmer', 'statecode' => 'RJ'],
            ['name' => 'Jalore', 'statecode' => 'RJ'],
            ['name' => 'Jhalawar', 'statecode' => 'RJ'],
            ['name' => 'Jhunjhunu', 'statecode' => 'RJ'],
            ['name' => 'Jodhpur', 'statecode' => 'RJ'],
            ['name' => 'Karauli', 'statecode' => 'RJ'],
            ['name' => 'Kota', 'statecode' => 'RJ'],
            ['name' => 'Nagaur', 'statecode' => 'RJ'],
            ['name' => 'Pali', 'statecode' => 'RJ'],
            ['name' => 'Pratapgarh', 'statecode' => 'RJ'],
            ['name' => 'Rajsamand', 'statecode' => 'RJ'],
            ['name' => 'Sawai Madhopur', 'statecode' => 'RJ'],
            ['name' => 'Sikar', 'statecode' => 'RJ'],
            ['name' => 'Sirohi', 'statecode' => 'RJ'],
            ['name' => 'Sri Ganganagar', 'statecode' => 'RJ'],
            ['name' => 'Tonk', 'statecode' => 'RJ'],
            ['name' => 'Udaipur', 'statecode' => 'RJ'],
            ['name' => 'Balotra', 'statecode' => 'RJ'],
            ['name' => 'Beawar', 'statecode' => 'RJ'],
            ['name' => 'Kekri', 'statecode' => 'RJ'],
            ['name' => 'Deeg', 'statecode' => 'RJ'],
            ['name' => 'Deedwana-Kuchaman', 'statecode' => 'RJ'],
            ['name' => 'Dudu', 'statecode' => 'RJ'],
            ['name' => 'Gangapur City', 'statecode' => 'RJ'],
            ['name' => 'Jaipur North', 'statecode' => 'RJ'],
            ['name' => 'Jaipur South', 'statecode' => 'RJ'],
            ['name' => 'Jodhpur East', 'statecode' => 'RJ'],
            ['name' => 'Jodhpur West', 'statecode' => 'RJ'],
            ['name' => 'Kotputli-Behror', 'statecode' => 'RJ'],
            ['name' => 'Khairthal', 'statecode' => 'RJ'],
            ['name' => 'Neem Ka Thana', 'statecode' => 'RJ'],
            ['name' => 'Phalodi', 'statecode' => 'RJ'],
            ['name' => 'Salumber', 'statecode' => 'RJ'],
            ['name' => 'Sanchore', 'statecode' => 'RJ'],
            ['name' => 'Shahpura', 'statecode' => 'RJ'],
            ['name' => 'Anupgarh', 'statecode' => 'RJ'],
            
            ['name' => 'Gangtok', 'statecode' => 'SK'],
            ['name' => 'Namchi', 'statecode' => 'SK'],
            ['name' => 'Mangan', 'statecode' => 'SK'],
            ['name' => 'Soreng', 'statecode' => 'SK'],
            ['name' => 'Pakyong', 'statecode' => 'SK'],
            ['name' => 'Gyalshing', 'statecode' => 'SK'],
            
            ['name' => 'Ariyalur', 'statecode' => 'TN'],
            ['name' => 'Chengalpattu', 'statecode' => 'TN'],
            ['name' => 'Chennai', 'statecode' => 'TN'],
            ['name' => 'Coimbatore', 'statecode' => 'TN'],
            ['name' => 'Cuddalore', 'statecode' => 'TN'],
            ['name' => 'Dharmapuri', 'statecode' => 'TN'],
            ['name' => 'Dindigul', 'statecode' => 'TN'],
            ['name' => 'Erode', 'statecode' => 'TN'],
            ['name' => 'Kallakurichi', 'statecode' => 'TN'],
            ['name' => 'Kancheepuram', 'statecode' => 'TN'],
            ['name' => 'Karur', 'statecode' => 'TN'],
            ['name' => 'Krishnagiri', 'statecode' => 'TN'],
            ['name' => 'Madurai', 'statecode' => 'TN'],
            ['name' => 'Mayiladuthurai', 'statecode' => 'TN'],
            ['name' => 'Nagapattinam', 'statecode' => 'TN'],
            ['name' => 'Kanniyakumari', 'statecode' => 'TN'],
            ['name' => 'Namakkal', 'statecode' => 'TN'],
            ['name' => 'Perambalur', 'statecode' => 'TN'],
            ['name' => 'Pudukottai', 'statecode' => 'TN'],
            ['name' => 'Ramanathapuram', 'statecode' => 'TN'],
            ['name' => 'Ranipet', 'statecode' => 'TN'],
            ['name' => 'Salem', 'statecode' => 'TN'],
            ['name' => 'Sivagangai', 'statecode' => 'TN'],
            ['name' => 'Tenkasi', 'statecode' => 'TN'],
            ['name' => 'Thanjavur', 'statecode' => 'TN'],
            ['name' => 'Theni', 'statecode' => 'TN'],
            ['name' => 'Thiruvallur', 'statecode' => 'TN'],
            ['name' => 'Thiruvarur', 'statecode' => 'TN'],
            ['name' => 'Thoothukudi', 'statecode' => 'TN'],
            ['name' => 'Trichirappalli', 'statecode' => 'TN'],
            ['name' => 'Thirunelveli', 'statecode' => 'TN'],
            ['name' => 'Tirupathur', 'statecode' => 'TN'],
            ['name' => 'Tiruppur', 'statecode' => 'TN'],
            ['name' => 'Tiruvannamalai', 'statecode' => 'TN'],
            ['name' => 'The Nilgiris', 'statecode' => 'TN'],
            ['name' => 'Vellore', 'statecode' => 'TN'],
            ['name' => 'Viluppuram', 'statecode' => 'TN'],
            ['name' => 'Virudhunagar', 'statecode' => 'TN'],
            
            ['name' => 'ADILABAD', 'statecode' => 'TG'],
            ['name' => 'BHADRADRI KOTHAGUDEM', 'statecode' => 'TG'],
            ['name' => 'HANUMAKONDA', 'statecode' => 'TG'],
            ['name' => 'HYDERABAD', 'statecode' => 'TG'],
            ['name' => 'JAGTIAL', 'statecode' => 'TG'],
            ['name' => 'JANGOAN', 'statecode' => 'TG'],
            ['name' => 'JAYASHANKAR BHOOPALPALLY', 'statecode' => 'TG'],
            ['name' => 'JOGULAMBA GADWAL', 'statecode' => 'TG'],
            ['name' => 'KAMAREDDY', 'statecode' => 'TG'],
            ['name' => 'KARIMNAGAR', 'statecode' => 'TG'],
            ['name' => 'KHAMMAM', 'statecode' => 'TG'],
            ['name' => 'KOMARAM BHEEM ASIFABAD', 'statecode' => 'TG'],
            ['name' => 'MAHABUBABAD', 'statecode' => 'TG'],
            ['name' => 'MAHABUBNAGAR', 'statecode' => 'TG'],
            ['name' => 'MANCHERIAL', 'statecode' => 'TG'],
            ['name' => 'MEDAK', 'statecode' => 'TG'],
            ['name' => 'MEDCHAL-MALKAJGIRI', 'statecode' => 'TG'],
            ['name' => 'MULUG', 'statecode' => 'TG'],
            ['name' => 'NAGARKURNOOL', 'statecode' => 'TG'],
            ['name' => 'NALGONDA', 'statecode' => 'TG'],
            ['name' => 'NARAYANPET', 'statecode' => 'TG'],
            ['name' => 'NIRMAL', 'statecode' => 'TG'],
            ['name' => 'NIZAMABAD', 'statecode' => 'TG'],
            ['name' => 'PEDDAPALLI', 'statecode' => 'TG'],
            ['name' => 'RAJANNA SIRCILLA', 'statecode' => 'TG'],
            ['name' => 'RANGAREDDY', 'statecode' => 'TG'],
            ['name' => 'SANGAREDDY', 'statecode' => 'TG'],
            ['name' => 'SIDDIPET', 'statecode' => 'TG'],
            ['name' => 'SURYAPET', 'statecode' => 'TG'],
            ['name' => 'VIKARABAD', 'statecode' => 'TG'],
            ['name' => 'WANAPARTHY', 'statecode' => 'TG'],
            ['name' => 'WARANGAL', 'statecode' => 'TG'],
            ['name' => 'YADADRI BHUVANAGIRI', 'statecode' => 'TG'],

            ['name' => 'Gomati', 'statecode' => 'TR'],
            ['name' => 'Dhalai', 'statecode' => 'TR'],
            ['name' => 'North Tripura', 'statecode' => 'TR'],
            ['name' => 'Khowai', 'statecode' => 'TR'],
            ['name' => 'Sipahijila', 'statecode' => 'TR'],
            ['name' => 'West Tripura', 'statecode' => 'TR'],
            ['name' => 'Unakoti', 'statecode' => 'TR'],
            ['name' => 'South Tripura', 'statecode' => 'TR'],
            
            ['name' => 'Agra', 'statecode' => 'UP'],
            ['name' => 'Aligarh', 'statecode' => 'UP'],
            ['name' => 'PrayagRaj', 'statecode' => 'UP'],
            ['name' => 'Ambedkar Nagar', 'statecode' => 'UP'],
            ['name' => 'Amroha', 'statecode' => 'UP'],
            ['name' => 'Auraiya', 'statecode' => 'UP'],
            ['name' => 'Azamgarh', 'statecode' => 'UP'],
            ['name' => 'Badaun', 'statecode' => 'UP'],
            ['name' => 'Bahraich', 'statecode' => 'UP'],
            ['name' => 'Ballia', 'statecode' => 'UP'],
            ['name' => 'Balrampur', 'statecode' => 'UP'],
            ['name' => 'Banda District', 'statecode' => 'UP'],
            ['name' => 'Barabanki', 'statecode' => 'UP'],
            ['name' => 'Bareilly', 'statecode' => 'UP'],
            ['name' => 'Basti', 'statecode' => 'UP'],
            ['name' => 'Bijnor', 'statecode' => 'UP'],
            ['name' => 'Bulandshabr', 'statecode' => 'UP'],
            ['name' => 'Chandauli(Varanasi Dehat)', 'statecode' => 'UP'],
            ['name' => 'Chitrakoot', 'statecode' => 'UP'],
            ['name' => 'Deoria', 'statecode' => 'UP'],
            ['name' => 'Etah', 'statecode' => 'UP'],
            ['name' => 'Etawah', 'statecode' => 'UP'],
            ['name' => 'Faizabad', 'statecode' => 'UP'],
            ['name' => 'Fatehpur', 'statecode' => 'UP'],
            ['name' => 'Firozabad', 'statecode' => 'UP'],
            ['name' => 'Gautam Buddha Nagar', 'statecode' => 'UP'],
            ['name' => 'Ghaziabad', 'statecode' => 'UP'],
            ['name' => 'Ghazipur', 'statecode' => 'UP'],
            ['name' => 'Gonda', 'statecode' => 'UP'],
            ['name' => 'Gorakhpur', 'statecode' => 'UP'],
            ['name' => 'Hamirpur', 'statecode' => 'UP'],
            ['name' => 'Hapur District', 'statecode' => 'UP'],
            ['name' => 'Hardoi', 'statecode' => 'UP'],
            ['name' => 'Hathras', 'statecode' => 'UP'],
            ['name' => 'Jaunpur District', 'statecode' => 'UP'],
            ['name' => 'Jhansi', 'statecode' => 'UP'],
            ['name' => 'Kannauj', 'statecode' => 'UP'],
            ['name' => 'Kanpur Dehat', 'statecode' => 'UP'],
            ['name' => 'Kanpur Nagar', 'statecode' => 'UP'],
            ['name' => 'Kasganj', 'statecode' => 'UP'],
            ['name' => 'Kaushambi', 'statecode' => 'UP'],
            ['name' => 'Kushinagar', 'statecode' => 'UP'],
            ['name' => 'Lakhimpur Kheri', 'statecode' => 'UP'],
            ['name' => 'Lalitpur', 'statecode' => 'UP'],
            ['name' => 'Lucknow', 'statecode' => 'UP'],
            ['name' => 'Maharajganj', 'statecode' => 'UP'],
            ['name' => 'Mahoba', 'statecode' => 'UP'],
            ['name' => 'Mainpuri', 'statecode' => 'UP'],
            ['name' => 'Mathura', 'statecode' => 'UP'],
            ['name' => 'Mau', 'statecode' => 'UP'],
            ['name' => 'Meerut', 'statecode' => 'UP'],
            ['name' => 'Mirzapur', 'statecode' => 'UP'],
            ['name' => 'Moradabad', 'statecode' => 'UP'],
            ['name' => 'Muzzaffarnagar', 'statecode' => 'UP'],
            ['name' => 'Pilibhit', 'statecode' => 'UP'],
            ['name' => 'Pratapgarh', 'statecode' => 'UP'],
            ['name' => 'Rae Bareli', 'statecode' => 'UP'],
            ['name' => 'Rampur', 'statecode' => 'UP'],
            ['name' => 'Saharanpur', 'statecode' => 'UP'],
            ['name' => 'Sant Kabir Nagar', 'statecode' => 'UP'],
            ['name' => 'Sant Ravidas Nagar', 'statecode' => 'UP'],
            ['name' => 'Sambhal', 'statecode' => 'UP'],
            ['name' => 'Shahjahanpur', 'statecode' => 'UP'],
            ['name' => 'Shamli', 'statecode' => 'UP'],
            ['name' => 'Shravasti', 'statecode' => 'UP'],
            ['name' => 'Siddhartnagar', 'statecode' => 'UP'],
            ['name' => 'Sitapur', 'statecode' => 'UP'],
            ['name' => 'Sonbhadra', 'statecode' => 'UP'],
            ['name' => 'Sultanpur', 'statecode' => 'UP'],
            ['name' => 'Unnao', 'statecode' => 'UP'],
            ['name' => 'Varanasi(Kashi)', 'statecode' => 'UP'],
            ['name' => 'Allahabad', 'statecode' => 'UP'],
            ['name' => 'Amethi', 'statecode' => 'UP'],
            ['name' => 'Bagpat', 'statecode' => 'UP'],
            ['name' => 'Farrukhabad', 'statecode' => 'UP'],
            
            ['name' => 'Almora', 'statecode' => 'UT'],
            ['name' => 'Bageshwar', 'statecode' => 'UT'],
            ['name' => 'Chamoli', 'statecode' => 'UT'],
            ['name' => 'Champawat', 'statecode' => 'UT'],
            ['name' => 'Dehradun', 'statecode' => 'UT'],
            ['name' => 'Haridwar', 'statecode' => 'UT'],
            ['name' => 'Nainital', 'statecode' => 'UT'],
            ['name' => 'Pauri Garhwal', 'statecode' => 'UT'],
            ['name' => 'Pithoragarh', 'statecode' => 'UT'],
            ['name' => 'Rudraprayag', 'statecode' => 'UT'],
            ['name' => 'Tehri Garhwal', 'statecode' => 'UT'],
            ['name' => 'Udham Singh Nagar', 'statecode' => 'UT'],
            ['name' => 'Uttarkashi', 'statecode' => 'UT'],
            
            ['name' => 'Alipurduar', 'statecode' => 'WB'],
            ['name' => 'Bankura', 'statecode' => 'WB'],
            ['name' => 'Birbhum', 'statecode' => 'WB'],
            ['name' => 'Cooch Behar', 'statecode' => 'WB'],
            ['name' => 'Dakshin Dinajpur', 'statecode' => 'WB'],
            ['name' => 'Darjeeling', 'statecode' => 'WB'],
            ['name' => 'Hooghly', 'statecode' => 'WB'],
            ['name' => 'Howrah', 'statecode' => 'WB'],
            ['name' => 'Jalpaiguri', 'statecode' => 'WB'],
            ['name' => 'Jhargam', 'statecode' => 'WB'],
            ['name' => 'Kalimpong', 'statecode' => 'WB'],
            ['name' => 'Kolkata', 'statecode' => 'WB'],
            ['name' => 'Malda', 'statecode' => 'WB'],
            ['name' => 'Murshidabad', 'statecode' => 'WB'],
            ['name' => 'Nadia', 'statecode' => 'WB'],
            ['name' => 'North 24 Parganas', 'statecode' => 'WB'],
            ['name' => 'Paschim Bardhaman', 'statecode' => 'WB'],
            ['name' => 'Purba Bardhaman', 'statecode' => 'WB'],
            ['name' => 'Purba Medinipur', 'statecode' => 'WB'],
            ['name' => 'Purulia', 'statecode' => 'WB'],
            ['name' => 'South 24 Parganas', 'statecode' => 'WB'],
            ['name' => 'Uttar Dinajpur', 'statecode' => 'WB'],
            ['name' => 'Pashcim Medinipur', 'statecode' => 'WB'], 
        ];
        DistrictModel::insert($districts);
    }
}

