<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DistrictModel;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
            ['name' => 'Kullu', 'statecode' => 'HP'],
            ['name' => 'Mandi', 'statecode' => 'HP'],
            ['name' => 'Bilaspur', 'statecode' => 'HP'],
            ['name' => 'Hamirpur', 'statecode' => 'HP'],
            ['name' => 'Solan', 'statecode' => 'HP'],
            ['name' => 'Shimla', 'statecode' => 'HP'],
            ['name' => 'Chamba', 'statecode' => 'HP'],
            ['name' => 'Kangra', 'statecode' => 'HP'],
            ['name' => 'Kinnaur', 'statecode' => 'HP'],
            ['name' => 'Una', 'statecode' => 'HP'],
            ['name' => 'Lahaul and Spiti', 'statecode' => 'HP'],
            ['name' => 'Sirmaur', 'statecode' => 'HP'],

            ['name' => 'East Godavari', 'statecode' => 'AP'],
            ['name' => 'West Godavari', 'statecode' => 'AP'],
            ['name' => 'Visakhapatnam', 'statecode' => 'AP'],
            ['name' => 'Srikakulam', 'statecode' => 'AP'],
            ['name' => 'Krishna', 'statecode' => 'AP'],
            ['name' => 'Kurnool', 'statecode' => 'AP'],
            ['name' => 'Guntur', 'statecode' => 'AP'],
            ['name' => 'Prakasam', 'statecode' => 'AP'],
            ['name' => 'Vizianagaram', 'statecode' => 'AP'],
            ['name' => 'Anantapur', 'statecode' => 'AP'],
            ['name' => 'Chittoor', 'statecode' => 'AP'],
            ['name' => 'Kadapa', 'statecode' => 'AP'],
            ['name' => 'Eluru', 'statecode' => 'AP'],
            ['name' => 'Bapatla', 'statecode' => 'AP'],
            ['name' => 'YSR District', 'statecode' => 'AP'],
            ['name' => 'Kakinada', 'statecode' => 'AP'],
            ['name' => 'Sri Potti Sriramulu Nellore', 'statecode' => 'AP'],
            ['name' => 'Nellore', 'statecode' => 'AP'],
            ['name' => 'Nandyal', 'statecode' => 'AP'],
            ['name' => 'Vijayawada', 'statecode' => 'AP'],
            ['name' => 'Anakapalli', 'statecode' => 'AP'],
            ['name' => 'Tirupati', 'statecode' => 'AP'],
            ['name' => 'Palnadu', 'statecode' => 'AP'],
            ['name' => 'Machilipatnam', 'statecode' => 'AP'],
            ['name' => 'Parvathipuram Manyam', 'statecode' => 'AP'],
            ['name' => 'Alluri Sitharama Raju', 'statecode' => 'AP'],

            ['name' => 'Anjaw', 'statecode' => 'AR'],
            ['name' => 'Changlang', 'statecode' => 'AR'],
            ['name' => 'Kamle', 'statecode' => 'AR'],
            ['name' => 'Kra Daadi', 'statecode' => 'AR'],
            ['name' => 'Kurung Kumey', 'statecode' => 'AR'],
            ['name' => 'Lepa-Rada', 'statecode' => 'AR'],
            ['name' => 'Lohit', 'statecode' => 'AR'],
            ['name' => 'Longding', 'statecode' => 'AR'],
            ['name' => 'Namsai', 'statecode' => 'AR'],
            ['name' => 'Pakke-Kessang', 'statecode' => 'AR'],
            ['name' => 'Papum Pare', 'statecode' => 'AR'],
            ['name' => 'Shi-Yomi', 'statecode' => 'AR'],
            ['name' => 'Siang', 'statecode' => 'AR'],
            ['name' => 'Tawang', 'statecode' => 'AR'],
            ['name' => 'Tirap', 'statecode' => 'AR'],
            ['name' => 'Lower Dibang Valley', 'statecode' => 'AR'],
            ['name' => 'Dibang Valley', 'statecode' => 'AR'],
            ['name' => 'East Kameng', 'statecode' => 'AR'],
            ['name' => 'West Kameng', 'statecode' => 'AR'],
            ['name' => 'East Siang', 'statecode' => 'AR'],
            ['name' => 'Lower Siang', 'statecode' => 'AR'],
            ['name' => 'Upper Siang', 'statecode' => 'AR'],
            ['name' => 'West Siang', 'statecode' => 'AR'],
            ['name' => 'Lower Subansiri', 'statecode' => 'AR'],
            ['name' => 'Upper Subansiri', 'statecode' => 'AR'],
            
            ['name' => 'Baksa', 'statecode' => 'AS'],
            ['name' => 'Barpeta', 'statecode' => 'AS'],
            ['name' => 'Bongaigaon', 'statecode' => 'AS'],
            ['name' => 'Cachar', 'statecode' => 'AS'],
            ['name' => 'Charaideo', 'statecode' => 'AS'],
            ['name' => 'Chirang', 'statecode' => 'AS'],
            ['name' => 'Darrang', 'statecode' => 'AS'],
            ['name' => 'Dhemaji', 'statecode' => 'AS'],
            ['name' => 'Dhubri', 'statecode' => 'AS'],
            ['name' => 'Dibrugarh', 'statecode' => 'AS'],
            ['name' => 'Dima Hasao', 'statecode' => 'AS'],
            ['name' => 'Goalpara', 'statecode' => 'AS'],
            ['name' => 'Golaghat', 'statecode' => 'AS'],
            ['name' => 'Hailakandi', 'statecode' => 'AS'],
            ['name' => 'Jorhat', 'statecode' => 'AS'],
            ['name' => 'Kamrup Metropolitan', 'statecode' => 'AS'],
            ['name' => 'Kamrup', 'statecode' => 'AS'],
            ['name' => 'Karbi Anglong', 'statecode' => 'AS'],
            ['name' => 'Karimganj', 'statecode' => 'AS'],
            ['name' => 'Kokrajhar', 'statecode' => 'AS'],
            ['name' => 'Lakhimpur', 'statecode' => 'AS'],
            ['name' => 'Majuli', 'statecode' => 'AS'],
            ['name' => 'Morigaon', 'statecode' => 'AS'],
            ['name' => 'Nagaon', 'statecode' => 'AS'],
            ['name' => 'Nalbari', 'statecode' => 'AS'],
            ['name' => 'Sivasagar', 'statecode' => 'AS'],
            ['name' => 'Sonitpur', 'statecode' => 'AS'],
            ['name' => 'South Salmara-Mankachar[', 'statecode' => 'AS'],
            ['name' => 'Tinsukia', 'statecode' => 'AS'],
            ['name' => 'Udalguri', 'statecode' => 'AS'],
            ['name' => 'West Karbi Anglong', 'statecode' => 'AS'],
            
            ['name' => 'Araria', 'statecode' => 'BR'],
            ['name' => 'Arwal', 'statecode' => 'BR'],
            ['name' => 'Aurangabad', 'statecode' => 'BR'],
            ['name' => 'Banka', 'statecode' => 'BR'],
            ['name' => 'Begusarai', 'statecode' => 'BR'],
            ['name' => 'Bhagalpur', 'statecode' => 'BR'],
            ['name' => 'Bhojpur', 'statecode' => 'BR'],
            ['name' => 'Buxar', 'statecode' => 'BR'],
            ['name' => 'Darbhanga', 'statecode' => 'BR'],
            ['name' => 'East Champaran', 'statecode' => 'BR'],
            ['name' => 'Gaya', 'statecode' => 'BR'],
            ['name' => 'Gopalganj', 'statecode' => 'BR'],
            ['name' => 'Jamui', 'statecode' => 'BR'],
            ['name' => 'Jehanabad', 'statecode' => 'BR'],
            ['name' => 'Kaimur', 'statecode' => 'BR'],
            ['name' => 'Katihar', 'statecode' => 'BR'],
            ['name' => 'Khagaria', 'statecode' => 'BR'],
            ['name' => 'Kishanganj', 'statecode' => 'BR'],
            ['name' => 'Lakhisarai', 'statecode' => 'BR'],
            ['name' => 'Madhepura', 'statecode' => 'BR'],
            ['name' => 'Madhubani', 'statecode' => 'BR'],
            ['name' => 'Munger', 'statecode' => 'BR'],
            ['name' => 'Muzaffarpur', 'statecode' => 'BR'],
            ['name' => 'Nalanda', 'statecode' => 'BR'],
            ['name' => 'Nawada', 'statecode' => 'BR'],
            ['name' => 'Patna', 'statecode' => 'BR'],
            ['name' => 'Purnia', 'statecode' => 'BR'],
            ['name' => 'Rohtas', 'statecode' => 'BR'],
            ['name' => 'Saharsa', 'statecode' => 'BR'],
            ['name' => 'Samastipur', 'statecode' => 'BR'],
            ['name' => 'Saran', 'statecode' => 'BR'],
            ['name' => 'Sheikhpura', 'statecode' => 'BR'],
            ['name' => 'Sheohar', 'statecode' => 'BR'],
            ['name' => 'Sitamarhi', 'statecode' => 'BR'],
            ['name' => 'Siwan', 'statecode' => 'BR'],
            ['name' => 'Supaul', 'statecode' => 'BR'],
            ['name' => 'Vaishali', 'statecode' => 'BR'],
            ['name' => 'West Champaran', 'statecode' => 'BR'],
            
            ['name' => 'Raipur', 'statecode' => 'CG'],
            ['name' => 'Balod', 'statecode' => 'CG'],
            ['name' => 'Baloda Bazar', 'statecode' => 'CG'],
            ['name' => 'Balrampur', 'statecode' => 'CG'],
            ['name' => 'Bastar', 'statecode' => 'CG'],
            ['name' => 'Bemetara', 'statecode' => 'CG'],
            ['name' => 'Bijapur', 'statecode' => 'CG'],
            ['name' => 'Bilaspur', 'statecode' => 'CG'],
            ['name' => 'Dantewada', 'statecode' => 'CG'],
            ['name' => 'Dhamtari', 'statecode' => 'CG'],
            ['name' => 'Durg', 'statecode' => 'CG'],
            ['name' => 'Gariaband', 'statecode' => 'CG'],
            ['name' => 'Gaurella-Pendra-Marwahi', 'statecode' => 'CG'],
            ['name' => 'Janjgir-Champa', 'statecode' => 'CG'],
            ['name' => 'Jashpur', 'statecode' => 'CG'],
            ['name' => 'Kabirdham', 'statecode' => 'CG'],
            ['name' => 'Kanker', 'statecode' => 'CG'],
            ['name' => 'Kondagaon', 'statecode' => 'CG'],
            ['name' => 'Khairagarh-Chhuikhadan-Gandai', 'statecode' => 'CG'],
            ['name' => 'Korba', 'statecode' => 'CG'],
            ['name' => 'Koriya', 'statecode' => 'CG'],
            ['name' => 'Mahasamund', 'statecode' => 'CG'],
            ['name' => 'Manendragarh-Chirmiri-Bharatpur', 'statecode' => 'CG'],
            ['name' => 'Mohla-Manpur- Ambagarh Chowki', 'statecode' => 'CG'],
            ['name' => 'Mungeli', 'statecode' => 'CG'],
            ['name' => 'Narayanpur', 'statecode' => 'CG'],
            ['name' => 'Raigarh', 'statecode' => 'CG'],
            ['name' => 'Rajnandgaon', 'statecode' => 'CG'],
            ['name' => 'Sarangarh-Bilaigarh', 'statecode' => 'CG'],
            ['name' => 'Sakti', 'statecode' => 'CG'],
            ['name' => 'Sukma', 'statecode' => 'CG'],
            ['name' => 'Surajpur', 'statecode' => 'CG'],
            ['name' => 'Surguja', 'statecode' => 'CG'],
            
            ['name' => 'North Goa', 'statecode' => 'GA'],
            ['name' => 'South Goa', 'statecode' => 'GA'],
            
            ['name' => 'Ahmedabad', 'statecode' => 'GJ'],
            ['name' => 'Amreli', 'statecode' => 'GJ'],
            ['name' => 'Anand', 'statecode' => 'GJ'],
            ['name' => 'Aravali', 'statecode' => 'GJ'],
            ['name' => 'Banaskantha', 'statecode' => 'GJ'],
            ['name' => 'Bharuch', 'statecode' => 'GJ'],
            ['name' => 'Bhavnagar', 'statecode' => 'GJ'],
            ['name' => 'Botad', 'statecode' => 'GJ'],
            ['name' => 'Chhota Udaipur', 'statecode' => 'GJ'],
            ['name' => 'Dahod', 'statecode' => 'GJ'],
            ['name' => 'Dang', 'statecode' => 'GJ'],
            ['name' => 'Devbhumi Dwarka', 'statecode' => 'GJ'],
            ['name' => 'Gandhinagar', 'statecode' => 'GJ'],
            ['name' => 'Gir Somnath', 'statecode' => 'GJ'],
            ['name' => 'Jamnagar', 'statecode' => 'GJ'],
            ['name' => 'Junagarh', 'statecode' => 'GJ'],
            ['name' => 'Kheda', 'statecode' => 'GJ'],
            ['name' => 'Kutch', 'statecode' => 'GJ'],
            ['name' => 'Mahisagar', 'statecode' => 'GJ'],
            ['name' => 'Mehsana', 'statecode' => 'GJ'],
            ['name' => 'Morbi', 'statecode' => 'GJ'],
            ['name' => 'Narmada', 'statecode' => 'GJ'],
            ['name' => 'Navsari', 'statecode' => 'GJ'],
            ['name' => 'Panchmahal', 'statecode' => 'GJ'],
            ['name' => 'Patan', 'statecode' => 'GJ'],
            ['name' => 'Porbandar', 'statecode' => 'GJ'],
            ['name' => 'Rajkot', 'statecode' => 'GJ'],
            ['name' => 'Sabarkantha', 'statecode' => 'GJ'],
            ['name' => 'Surat', 'statecode' => 'GJ'],
            ['name' => 'Surendranagar', 'statecode' => 'GJ'],
            ['name' => 'Tapi', 'statecode' => 'GJ'],
            ['name' => 'Vadodara', 'statecode' => 'GJ'],
            ['name' => 'Valsad', 'statecode' => 'GJ'],
            
            ['name' => 'Ambala', 'statecode' => 'HR'],
            ['name' => 'Bhiwani', 'statecode' => 'HR'],
            ['name' => 'Charkhi Dadri', 'statecode' => 'HR'],
            ['name' => 'Faridabad', 'statecode' => 'HR'],
            ['name' => 'Fatehabad', 'statecode' => 'HR'],
            ['name' => 'Gurugram', 'statecode' => 'HR'],
            ['name' => 'Hisar', 'statecode' => 'HR'],
            ['name' => 'Jhajjar', 'statecode' => 'HR'],
            ['name' => 'Jind', 'statecode' => 'HR'],
            ['name' => 'Kaithal', 'statecode' => 'HR'],
            ['name' => 'Karnal', 'statecode' => 'HR'],
            ['name' => 'Kurukshetra', 'statecode' => 'HR'],
            ['name' => 'Mahendragarh', 'statecode' => 'HR'],
            ['name' => 'Nuh', 'statecode' => 'HR'],
            ['name' => 'Palwal', 'statecode' => 'HR'],
            ['name' => 'Panchkula', 'statecode' => 'HR'],
            ['name' => 'Panipat', 'statecode' => 'HR'],
            ['name' => 'Rewari', 'statecode' => 'HR'],
            ['name' => 'Rohtak', 'statecode' => 'HR'],
            ['name' => 'Sirsa', 'statecode' => 'HR'],
            ['name' => 'Sonipat', 'statecode' => 'HR'],
            ['name' => 'Yamunanagar', 'statecode' => 'HR'],
            
            ['name' => 'Bokaro', 'statecode' => 'JH'],
            ['name' => 'Chatra', 'statecode' => 'JH'],
            ['name' => 'Deoghar', 'statecode' => 'JH'],
            ['name' => 'Dhanbad', 'statecode' => 'JH'],
            ['name' => 'Dumka', 'statecode' => 'JH'],
            ['name' => 'East Singhbhum', 'statecode' => 'JH'],
            ['name' => 'Garhwa', 'statecode' => 'JH'],
            ['name' => 'Giridih', 'statecode' => 'JH'],
            ['name' => 'Godda', 'statecode' => 'JH'],
            ['name' => 'Gumla', 'statecode' => 'JH'],
            ['name' => 'Hazaribag', 'statecode' => 'JH'],
            ['name' => 'Jamtara', 'statecode' => 'JH'],
            ['name' => 'Khunti', 'statecode' => 'JH'],
            ['name' => 'Koderma', 'statecode' => 'JH'],
            ['name' => 'Latehar', 'statecode' => 'JH'],
            ['name' => 'Lohardaga', 'statecode' => 'JH'],
            ['name' => 'Pakur', 'statecode' => 'JH'],
            ['name' => 'Palamu', 'statecode' => 'JH'],
            ['name' => 'Ramgarh', 'statecode' => 'JH'],
            ['name' => 'Ranchi', 'statecode' => 'JH'],
            ['name' => 'Sahibganj', 'statecode' => 'JH'],
            ['name' => 'Seraikela-Kharsawan', 'statecode' => 'JH'],
            ['name' => 'Simdega', 'statecode' => 'JH'],
            ['name' => 'West Singhbhum', 'statecode' => 'JH'],
            
            ['name' => 'Bagalkote', 'statecode' => 'KA'],
            ['name' => 'Bengaluru Urban', 'statecode' => 'KA'],
            ['name' => 'Bengaluru Rural', 'statecode' => 'KA'],
            ['name' => 'Belagavi', 'statecode' => 'KA'],
            ['name' => 'Ballary', 'statecode' => 'KA'],
            ['name' => 'Bidar', 'statecode' => 'KA'],
            ['name' => 'Vijayapura', 'statecode' => 'KA'],
            ['name' => 'Chamarajanagara', 'statecode' => 'KA'],
            ['name' => 'Chikkaballapura', 'statecode' => 'KA'],
            ['name' => 'Chikkamagaluru', 'statecode' => 'KA'],
            ['name' => 'Chitradurga', 'statecode' => 'KA'],
            ['name' => 'Dakshina Kannada', 'statecode' => 'KA'],
            ['name' => 'Davanagere', 'statecode' => 'KA'],
            ['name' => 'Dharwad', 'statecode' => 'KA'],
            ['name' => 'Gadag', 'statecode' => 'KA'],
            ['name' => 'Kalaburagi', 'statecode' => 'KA'],
            ['name' => 'Hassan', 'statecode' => 'KA'],
            ['name' => 'Haveri', 'statecode' => 'KA'],
            ['name' => 'Kodagu', 'statecode' => 'KA'],
            ['name' => 'Kolara', 'statecode' => 'KA'],
            ['name' => 'Koppala', 'statecode' => 'KA'],
            ['name' => 'Mandya', 'statecode' => 'KA'],
            ['name' => 'Mysuru', 'statecode' => 'KA'],
            ['name' => 'Raichuru', 'statecode' => 'KA'],
            ['name' => 'Ramanagara', 'statecode' => 'KA'],
            ['name' => 'Shivamogga', 'statecode' => 'KA'],
            ['name' => 'Tumakuru', 'statecode' => 'KA'],
            ['name' => 'Udupi', 'statecode' => 'KA'],
            ['name' => 'Uttara Kannada', 'statecode' => 'KA'],
            ['name' => 'Vijayanagara', 'statecode' => 'KA'],
            ['name' => 'Yadgiri', 'statecode' => 'KA'],
            
        ];
        DistrictModel::insert($districts);
    }
}

